package com.aura.core.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

data class AuraAuthTokens(
    val backgroundColor: Color,
    val textColor: Color,
    val labelColor: Color,
    val placeholderColor: Color,
    val primaryColor: Color,
    val buttonGradientEnd: Color,
    val errorColor: Color,
    val cardShadowColor: Color,
    val cardShadowAlpha: Float,
    val cardSurfaceColor: Color,
    val screenHorizontalPadding: Dp,
    val screenVerticalPadding: Dp,
    val bottomSpacer: Dp,
    val cardOuterHorizontalPadding: Dp,
    val cardRadius: Dp,
    val cardShadowElevation: Dp,
    val cardHorizontalPadding: Dp,
    val cardVerticalPadding: Dp,
    val titleFontSize: TextUnit,
    val titleBottomGapLogin: Dp,
    val titleBottomGapRegister: Dp,
    val nameRowGap: Dp,
    val nameRowBottomGap: Dp,
    val fieldGapLogin: Dp,
    val fieldGapRegister: Dp,
    val forgotTopGap: Dp,
    val forgotFontSize: TextUnit,
    val forgotAlpha: Float,
    val submitTopGap: Dp,
    val submitHeight: Dp,
    val submitRadius: Dp,
    val submitShadowElevation: Dp,
    val submitShadowAlpha: Float,
    val submitProgressSize: Dp,
    val submitProgressStroke: Dp,
    val submitTextFontSize: TextUnit,
    val submitTextLetterSpacing: TextUnit,
    val submitIconGap: Dp,
    val submitIconSize: Dp,
    val errorTopGap: Dp,
    val errorFontSize: TextUnit,
    val modeToggleTopGap: Dp,
    val modeToggleFontSize: TextUnit,
    val fieldLabelFontSize: TextUnit,
    val fieldLabelLetterSpacing: TextUnit,
    val fieldLabelBottomGap: Dp,
    val fieldTextFontSize: TextUnit,
    val fieldHeight: Dp,
    val fieldBorderAlpha: Float,
    val fieldRadius: Dp,
    val fieldStartPadding: Dp,
    val fieldEndPadding: Dp,
    val passwordIconSize: Dp,
    val glassBorderWidth: Dp,
    val glassSurfaceColor: Color,
    val glassBorderColor: Color,
)

fun defaultAuraAuthTokens() = AuraAuthTokens(
    backgroundColor = Color(0xFFF4F7FE),
    textColor = Color(0xFF2D3648),
    labelColor = Color(0xFF434655).copy(alpha = 0.7f),
    placeholderColor = Color(0xFF434655).copy(alpha = 0.3f),
    primaryColor = Color(0xFFF472B6),
    buttonGradientEnd = Color(0xFFFBCFE8),
    errorColor = Color(0xFFEF4444),
    cardShadowColor = Color(0xFF1F2687),
    cardShadowAlpha = 0.05f,
    cardSurfaceColor = Color(0xFFF2F5FA),
    screenHorizontalPadding = 24.dp,
    screenVerticalPadding = 32.dp,
    bottomSpacer = 24.dp,
    cardOuterHorizontalPadding = 4.dp,
    cardRadius = 32.dp,
    cardShadowElevation = 8.dp,
    cardHorizontalPadding = 24.dp,
    cardVerticalPadding = 32.dp,
    titleFontSize = 24.sp,
    titleBottomGapLogin = 24.dp,
    titleBottomGapRegister = 20.dp,
    nameRowGap = 16.dp,
    nameRowBottomGap = 16.dp,
    fieldGapLogin = 16.dp,
    fieldGapRegister = 12.dp,
    forgotTopGap = 12.dp,
    forgotFontSize = 12.sp,
    forgotAlpha = 0.7f,
    submitTopGap = 24.dp,
    submitHeight = 56.dp,
    submitRadius = 16.dp,
    submitShadowElevation = 8.dp,
    submitShadowAlpha = 0.2f,
    submitProgressSize = 24.dp,
    submitProgressStroke = 2.dp,
    submitTextFontSize = 14.sp,
    submitTextLetterSpacing = 0.5.sp,
    submitIconGap = 8.dp,
    submitIconSize = 18.dp,
    errorTopGap = 12.dp,
    errorFontSize = 13.sp,
    modeToggleTopGap = 28.dp,
    modeToggleFontSize = 14.sp,
    fieldLabelFontSize = 10.sp,
    fieldLabelLetterSpacing = 1.sp,
    fieldLabelBottomGap = 6.dp,
    fieldTextFontSize = 14.sp,
    fieldHeight = 48.dp,
    fieldBorderAlpha = 0.3f,
    fieldRadius = 12.dp,
    fieldStartPadding = 0.dp,
    fieldEndPadding = 12.dp,
    passwordIconSize = 20.dp,
    glassBorderWidth = 1.dp,
    glassSurfaceColor = Color.White,
    glassBorderColor = Color.White,
)
