package com.aura.core.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

data class AuraDiagnosticsTokens(
    val screenPadding: Dp,
    val headerBottomGap: Dp,
    val heroTopGap: Dp,
    val sectionGapLarge: Dp,
    val sectionGapMedium: Dp,
    val scanCardAlpha: Float,
    val scanTitleGap: Dp,
    val scanSubtitleGap: Dp,
    val secondaryTextAlpha: Float,
    val loadingTextAlpha: Float,
    val scanPulseInitialAlpha: Float,
    val scanPulseTargetAlpha: Float,
    val scanPulseDurationMillis: Int,
    val scanCanvasSize: Dp,
    val scanCanvasPadding: Dp,
    val scanStrokeWidth: Dp,
    val scanBaseRadiusInset: Dp,
    val scanRingGap: Dp,
    val scanRingAlphaStep: Float,
    val scanRingMinAlpha: Float,
    val scanIconSurfaceSize: Dp,
    val scanIconSurfaceAlpha: Float,
    val scanIconSurfaceElevation: Dp,
    val scanIconSize: Dp,
    val metricsGap: Dp,
    val sectionTitleStartPadding: Dp,
    val metricRowGap: Dp,
    val sensitivityColor: Color,
    val metricCardShadowElevation: Dp,
    val metricCardRadius: Dp,
    val metricCardShadowAlpha: Float,
    val metricCardGradientStartAlpha: Float,
    val metricCardGradientEndAlpha: Float,
    val metricCardPadding: Dp,
    val metricIconBottomGap: Dp,
    val metricValueBottomGap: Dp,
    val iotGap: Dp,
    val iotCardSurfaceAlpha: Float,
    val iotIconSurfaceSize: Dp,
    val iotIconSurfaceAlpha: Float,
    val iotIconSize: Dp,
    val iotContentGap: Dp,
    val iotStatusIconSize: Dp,
    val iotStatusGap: Dp,
    val batteryRadius: Dp,
    val batterySurfaceAlpha: Float,
    val batteryHorizontalPadding: Dp,
    val batteryVerticalPadding: Dp,
)

fun defaultAuraDiagnosticsTokens() = AuraDiagnosticsTokens(
    screenPadding = 16.dp,
    headerBottomGap = 16.dp,
    heroTopGap = 32.dp,
    sectionGapLarge = 32.dp,
    sectionGapMedium = 24.dp,
    scanCardAlpha = 0.08f,
    scanTitleGap = 16.dp,
    scanSubtitleGap = 8.dp,
    secondaryTextAlpha = 0.6f,
    loadingTextAlpha = 0.7f,
    scanPulseInitialAlpha = 0.3f,
    scanPulseTargetAlpha = 0.8f,
    scanPulseDurationMillis = 1000,
    scanCanvasSize = 180.dp,
    scanCanvasPadding = 16.dp,
    scanStrokeWidth = 4.dp,
    scanBaseRadiusInset = 20.dp,
    scanRingGap = 15.dp,
    scanRingAlphaStep = 0.15f,
    scanRingMinAlpha = 0.1f,
    scanIconSurfaceSize = 100.dp,
    scanIconSurfaceAlpha = 0.15f,
    scanIconSurfaceElevation = 8.dp,
    scanIconSize = 48.dp,
    metricsGap = 16.dp,
    sectionTitleStartPadding = 4.dp,
    metricRowGap = 16.dp,
    sensitivityColor = Color(0xFFFFAB40),
    metricCardShadowElevation = 6.dp,
    metricCardRadius = 16.dp,
    metricCardShadowAlpha = 0.1f,
    metricCardGradientStartAlpha = 0.12f,
    metricCardGradientEndAlpha = 0.05f,
    metricCardPadding = 16.dp,
    metricIconBottomGap = 8.dp,
    metricValueBottomGap = 4.dp,
    iotGap = 12.dp,
    iotCardSurfaceAlpha = 0.7f,
    iotIconSurfaceSize = 48.dp,
    iotIconSurfaceAlpha = 0.2f,
    iotIconSize = 24.dp,
    iotContentGap = 16.dp,
    iotStatusIconSize = 16.dp,
    iotStatusGap = 4.dp,
    batteryRadius = 8.dp,
    batterySurfaceAlpha = 0.2f,
    batteryHorizontalPadding = 12.dp,
    batteryVerticalPadding = 6.dp,
)
